<?php

namespace Bruens\CompanyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function save(\Bruens\CompanyBundle\Entity\Company $company, \Bruens\UserMgmtBundle\Entity\User $user = null)
    {
        $flexConnect = new \Bruens\FlexConnectBundle\Entity\FlexConnect();
        $flexConnect->setType(1);
        $flexConnect->setCompanies($company);
        
        $flexConnect->setUsers($user);
        //print_r($user);
        //$user->addFlexConnects($flexConnect);
        
        $em = $this->getEntityManager();
        $em->persist($flexConnect);
        $em->persist($company);
        $em->persist($user);
        //$em->persist($user);
        
        $em->flush();
        
    }
    private function getUser()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT u FROM BruensUserMgmtBundle:User u WHERE u.id = 1')
                ->getResult();
    }
}